### ISSUE TITLE
4.1 Edit Item

### ISSUE THREAD

**Issue by heinenandreas** [heinenandreas/capstone-project#10]
As a User
I need to add and edit Items to the list
to be able to add new items that I bought

## Description
By clicking a button a form should open where the user can add or edit an item, set the unit and choose the wanted amounts.

Scribble / design or text
![Add Item to List](https://github.com/heinenandreas/files/blob/main/itemlist-add-delete.png?raw=true)
![New Item](https://github.com/heinenandreas/files/blob/main/new-item.png?raw=true)
## Acceptance Criteria

- [ ]  button "add" on mainpage
- [ ] form with input for name and unit
- [ ] buttons to set min, max and actual amount of the item
- [ ] "create/safe" button
- [ ] "back/cancel" button

## Tasks

(for developers team)

- [ ] Add a button to the mainpage that opens a new form
- [ ] the form contains a safe button
- [ ] the form contains a cancel button
- [ ] add an input field for the item name
- [ ] add an input field for item unit
- [ ] add buttons to set and change min, max und actual amount
