### ISSUE TITLE
## Sort Items in Lists

### ISSUE THREAD

**Issue by heinenandreas** [heinenandreas/capstone-project#13]
**As a User** ...(user, Author, logged in User...)
**I need** to sort my created items in lists
**to be able to** to have a better overview on my existing items

## Description

Scribble / design or text

## Acceptance Criteria

- [ ] items should be displayed in lists, 
- [ ] categorized in different list depending on the "category"-value of each items

## Tasks

(for developers team)

- [ ] filter itemlist in each category
- [ ] map the filtered items
