### ISSUE TITLE
Create shoppinglist

### ISSUE THREAD

**Issue by heinenandreas** [heinenandreas/capstone-project#23]
**As a User** ...(user, Author, logged in User...)
**I need** a shoppinlist
**to be able to** habe an overview of the products that i need to rebuy

## Acceptance Criteria

- [ ] Shoppinglist is a new site
- [ ] it has a container to display the products
- [ ] only products should be listet that are under the min amount

## Tasks

- [ ] create shoppinglist. js
- [ ] style for headline an shoppinglist container
- [ ] function to display actual amount of each item under min amount

**Comment by SarmadAD** [comment]
Looks good!
