### ISSUE TITLE
3 Change amount with Buttons

### ISSUE THREAD

**Issue by heinenandreas** [heinenandreas/capstone-project#3]
As a User
I need change the min, max and actual amount of the items
to be able to adapt them to my consumption

Description

Scribble / design or text
Each item display needs an + & - button to set the wanted amount

## Acceptance Criteria

- [x] + Button for each amount
- [x] - Button for each amount

## Tasks

- [x] Add Buttons
- [x] the + Button should add 1 to the fitting amount when clicked 
- [x] the - Button should subtract 1 to the fitting amount when clicked
