### ISSUE TITLE
delete Item

### ISSUE THREAD

**Issue by heinenandreas** [heinenandreas/capstone-project#5]
**As a User** ...(user, Author, logged in User...)
**I need**  delete items
**to be able to** delete items that i do not longer need

## Description

![delete item](https://github.com/heinenandreas/files/blob/main/delete%20product.png?raw=true)

## Acceptance Criteria

- [ ] button to edit item
- [ ] warning message
- [ ] cancel button
- [ ] confirm button
- [ ] items should be removed from list after deletion

## Tasks

(for developers team)

- [ ] delete item component
- [ ]
